#!/usr/local/bin/php
<?php
namespace KS;

$root = __DIR__;

require_once "$root/vendor/autoload.php";

try {
    $cmd = new \Commando\Command();
    $cmd->option('c')
        ->aka('config-file')
        ->describedAs("The path defining the daemon's config file");

    // Get a config file path, or use default
    if (!$cmd['c']) {
        if (!($home = getenv("HOME"))) {
            $home = "/root";
        }
        $defaultOverride = true;
        $configFile = "$home/.config/ks/exchange-daemon.conf";
    } else {
        $defaultOverride = false;
        $configFile = realpath($cmd['c']);
    }

    $config = new ExchangeConfig("$root/config.php", $configFile);
    $exchange = new Exchange($config);
    $exchange->run();

} catch (\Throwable $e) {
    fwrite(STDERR, "Uh oh... Looks like an unrecoverable error :(. ".$e->getMessage()."\n\n");
    if (isset($exchange)) {
        $exchange->shutdown();
    }
    throw $e;
}


